"""update Project table

Revision ID: 44236491b7c1
Revises: 
Create Date: 2019-09-06 15:16:20.917676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44236491b7c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('describe', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'describe')
    op.drop_column('project', 'datetime')
    # ### end Alembic commands ###
